### ISSUE TITLE
Impl. enum State

### ISSUE THREAD

**Issue by grzkos** [grzkos/ModalCommLangGrunding#2]
[Niezwiązany]

szczególy:
operacje logiczne - proponuję tak jak dla przypadku logiki trójwartościowej SQLa (z NULLami - u nas UNKNOWN), tzn 
true and null = null
false and null = false
true or null = true
not null = null
itd.

operacje najlepiej dla generycznych operandów
coś analogicznego do: http://stackoverflow.com/questions/9678071/enum-as-arithmetic-operation

**Comment by Jarema27** [comment]
W trakcie implementacji,propozycja : 
Zamienić True,False,Unkown na Is,Is_Not,Mayhaps
Uzasadnienie : Nienaturalność brzmienia Stan:True albo Stan:False, formuła Stan:Is albo Stan:IsNot wydaje się dużo bardziej czytelna

**Comment by grzkos** [comment]
popieram
