### ISSUE TITLE
Impl. metody evaluate dla ComplexFormula

### ISSUE THREAD

**Issue by grzkos** [grzkos/ModalCommLangGrunding#3]
związany z 2f056180-0f33-11e7-9d3d-79d1aa8a7987grzkos/ModalCommLangGrunding#5 
nagłówek i typ zwracany określony w kodzie, chyba sie nie ma co rozwodzic

+ toString();

Pamiętajcie ze w przyszłości formuła wiązana będzie z modelem mentalnym.

**Comment by Jarema27** [comment]
Sprawdzenie poprawności

Complex + simple

**Comment by WeronikaWolska** [comment]
1. Konstruktor (drzewo)
2. Sprawdzenie poprawności formuly
3. Ewaluacja formuły złożonej
