### ISSUE TITLE
Impl. evaluate w SimpleFormula

### ISSUE THREAD

**Issue by grzkos** [grzkos/ModalCommLangGrunding#4]
zwiazany grzkos/ModalCommLangGrunding#2 

+toString()

**Comment by mgawlowski** [comment]
czy klasy tego typu nie powinny miec po prostu funkcji statycznych?

**Comment by mgawlowski** [comment]
zmienilem typ isNegated z State na boolean

**Comment by grzkos** [comment]
ad. 1
uważam że metoda jako składowa klasy powinna zostać, ponieważ w naszym zamyśle mieliśmy traktować każdą formułę jako kolejną instancję klasy SimpleFormula, co nam m.in. pozwoli w prosty sposób zbudować formułę złożoną z dwóch formuł prostych. @Jarema27 , @WeronikaWolska  powiedzcie jak Wy uważacie.

**Comment by grzkos** [comment]
ad. 2.1 Nie pamiętam jaki był powód ustawienia typu State - póki co ok
ad 2.2 ok

**Comment by Jarema27** [comment]
Funkcje statycznie nie wydają się mieć tutaj zbyt wielkiego sensu,wszstkie klasy mają tworzyć integralną logiczną całość.
