### ISSUE TITLE
Dopracowanie Object

### ISSUE THREAD

**Issue by grzkos** [grzkos/ModalCommLangGrunding#6]
niezwiazany
Impl. oznaczonych w kodzie metod + mile widziane ew własne inwencje 
zastanówcie się nad tym jak prawidlowo zaimplementować equals

**Comment by mgawlowski** [comment]
object ma jeszcze 3 x todo
chyba powinien wrocic do ready

**Comment by mgawlowski** [comment]
zwracany typ metody hasTrait zmieniam z State na boolean

**Comment by grzkos** [comment]
ad. 2 hmm, chyba masz racje, bo poziom obiektu to ten "obiektywny" poziom
ad.1 racja, chyba zamietliśmy problem pod dywan xD ale nie ma lekko, cofam to

**Comment by WeronikaWolska** [comment]
ad. 2 dlaczego boolean? To w końcu obiekty są tutaj obiektywną reprezentacją świata rzeczywistego czy subiektywną reprezentacją świata pamiętanego?

**Comment by Jarema27** [comment]
Weronika zadaje dobre pytanie,zwykły boolean może zawieść w kilku zadaniach

**Comment by grzkos** [comment]
Cały czas zapominam, że jakiekolwiek dane na jakich agent będzie pracował, to dane z BD zawierające dane zczytane z czujników - a tam rzeczywiście zdarzą się też dane niepewne. @WeronikaWolska masz rację, w ogóle powinniśmy sobie wybić z głowy na razie poziom obiektywizmu, bo to wszystko co piszemy dotyczy jednego agenta. 

W związku z tym jestem przychylny do wersji z typem State
